"""
Create the append-only manual correction queue used by the live app.

This table is intentionally separate from `practice_locations`, `practices`,
and `practice_intel`. UI edits land here first as review items; a later audited
pipeline step can apply accepted corrections to SQLite/Supabase. This prevents
casual live-app edits from mutating census truth or scorer inputs directly.

Idempotent on both Supabase Postgres and local SQLite.
"""
import os
import sqlite3

from sqlalchemy import create_engine, text

ROOT = "/Users/suleman/dental-pe-tracker"
ENV_PATHS = [os.path.join(ROOT, ".env"), os.path.join(ROOT, "dental-pe-nextjs", ".env.local")]

for path in ENV_PATHS:
    if not os.path.exists(path):
        continue
    for raw in open(path):
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        os.environ.setdefault(k.strip(), v.strip())

SQLITE_DB = os.path.join(ROOT, "data", "dental_pe_tracker.db")
TABLE = "practice_manual_corrections"

POSTGRES_DDL = f"""
CREATE TABLE IF NOT EXISTS {TABLE} (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id TEXT NOT NULL,
  npi TEXT,
  practice_name TEXT,
  field_key TEXT NOT NULL,
  old_value TEXT,
  suggested_value TEXT NOT NULL,
  source_url TEXT,
  notes TEXT,
  submitted_by TEXT,
  status TEXT NOT NULL DEFAULT 'queued',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT {TABLE}_field_key_check CHECK (
    field_key IN (
      'practice_name',
      'owner_doctor_or_group',
      'operating_doctors',
      'provider_count',
      'employee_count',
      'website',
      'general_note'
    )
  ),
  CONSTRAINT {TABLE}_status_check CHECK (
    status IN ('queued', 'applied', 'rejected')
  )
);
CREATE INDEX IF NOT EXISTS ix_{TABLE}_location_id ON {TABLE}(location_id);
CREATE INDEX IF NOT EXISTS ix_{TABLE}_status_created_at ON {TABLE}(status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_{TABLE}_field_key ON {TABLE}(field_key);
ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY;
"""

SQLITE_DDL = f"""
CREATE TABLE IF NOT EXISTS {TABLE} (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  location_id TEXT NOT NULL,
  npi TEXT,
  practice_name TEXT,
  field_key TEXT NOT NULL,
  old_value TEXT,
  suggested_value TEXT NOT NULL,
  source_url TEXT,
  notes TEXT,
  submitted_by TEXT,
  status TEXT NOT NULL DEFAULT 'queued',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_{TABLE}_location_id ON {TABLE}(location_id);
CREATE INDEX IF NOT EXISTS ix_{TABLE}_status_created_at ON {TABLE}(status, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_{TABLE}_field_key ON {TABLE}(field_key);
"""


def migrate_postgres() -> None:
    url = os.environ.get("SUPABASE_DATABASE_URL") or os.environ.get("DATABASE_URL")
    if not url:
        print("WARN: SUPABASE_DATABASE_URL / DATABASE_URL not set — skipping Supabase leg.")
        return

    print("== Supabase Postgres ==")
    engine = create_engine(url, pool_pre_ping=True)
    statements = [s.strip() for s in POSTGRES_DDL.split(";") if s.strip()]
    with engine.begin() as conn:
        conn.execute(text("SET statement_timeout = '120s'"))
        for stmt in statements:
            conn.execute(text(stmt))
    with engine.connect() as conn:
        count = conn.execute(
            text("""
                SELECT COUNT(*)
                FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = :table
            """),
            {"table": TABLE},
        ).scalar_one()
    print(f"  {TABLE}: {'PRESENT' if count else 'MISSING'}")


def migrate_sqlite() -> None:
    print("\n== SQLite ==")
    if not os.path.exists(SQLITE_DB):
        print(f"SKIP: {SQLITE_DB} not found")
        return
    conn = sqlite3.connect(SQLITE_DB)
    with conn:
        conn.executescript(SQLITE_DDL)
    exists = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
        (TABLE,),
    ).fetchone()
    print(f"  {TABLE}: {'PRESENT' if exists else 'MISSING'}")
    conn.close()


if __name__ == "__main__":
    migrate_postgres()
    migrate_sqlite()
    print("\nDone. Manual corrections queue is additive and append-only.")
